CSwala/CSwala-android

- CONTRIBUTING.md
Made few changes in 'Contributing Guidelines'.
In reference to, Issue #10
> Improvements in Contributing Guidelines

- app/build.gradle
> changed minSdkVersion to 22 with linked #17 issue

- app/build.gradle
- build.gradle
Fixes #18: Update some dependencies in build.gradle (module: app) and in build.gradle (project level).
> Update dependencies to newer version (CSwala#18)

- app/src/main/java/com/cswala/cswala/LoginActivity.java
Added scheduled fade-in animations to the Google & GitHub login buttons.
> #51 Issue Resolved : Added Fade-in Animation to Login buttons in LoginActivity

- .github/pull_request_template.md
> Added the template file for pull requests.

- app/src/main/java/com/cswala/cswala/JobHunt.java
- app/src/main/java/com/cswala/cswala/MainActivity.java
- app/src/main/res/layout/fragment_job_hunt.xml
Fixes #5:  Created a blank fragment for JobHunt in the navigation bar.
> Add JobHunt Fragment

- app/src/main/java/com/cswala/cswala/CommunityFragment.java
- app/src/main/java/com/cswala/cswala/MainActivity.java
- app/src/main/java/com/cswala/cswala/ProfileFragment.java
- app/src/main/res/layout/fragment_community.xml
- app/src/main/res/layout/fragment_profile.xml
- Fixes #4 and Fixes #6 : Created two new blank profile and community fragments for navigation bar.
> Add Profile and Community Fragment.

- app/src/main/java/com/cswala/cswala/ExploreFragment.java
- app/src/main/java/com/cswala/cswala/MainActivity.java
- app/src/main/res/layout/fragment_explore.xml
- Fixes #3 : Created new explore fragment for navigation bar.
> Add Explore Fragment

- app/src/main/java/com/cswala/cswala/MainActivity.java
Fixes #84 
Currently the app is staying on the main activity screen even after pressing back button numerous time.
I have added on back pressed function to resolve this issue ,by defining the function of back button
> Added onBackPressed function

- app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
- app/src/main/java/com/cswala/cswala/Fragments/ProfileFragment.java
- app/src/main/java/com/cswala/cswala/MainActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_community.xml
- app/src/main/res/layout/fragment_explore.xml
- app/src/main/res/layout/fragment_job_hunt.xml
- app/src/main/res/layout/fragment_news.xml
- app/src/main/res/layout/fragment_profile.xml
Fixes #67: Replaced logout textview from main activity to profile fragment.
Fixes #98: Removed auto sign-in into the previous account even after logout. Added Google client signout function along with the on success listener to login with a preferred account while signing in.
> Fix #67 and #98: Replace logout textview and fix Google sign-in bug

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cswala/cswala/Activities/TechDataActivity.java
- app/src/main/java/com/cswala/cswala/Adapters/TechListAdapter.java
- app/src/main/java/com/cswala/cswala/Adapters/techItemClicked.java
- app/src/main/java/com/cswala/cswala/Fragments/ExploreFragment.java
- app/src/main/java/com/cswala/cswala/MainActivity.java
- app/src/main/java/com/cswala/cswala/Models/TechListElement.java
- app/src/main/java/com/cswala/cswala/utils/IntentHelper.java
- app/src/main/res/drawable/search_background.xml
- app/src/main/res/layout/activity_tech_data.xml
- app/src/main/res/layout/fragment_explore.xml
- app/src/main/res/layout/tech_list_element.xml
- app/src/main/res/values/strings.xml
Fixes #99 
This PR completes the explore fragment logic part that is #99  and fetches data from the firestore and shows it in a different activity.
> created ExploreFragment and it's logic part.

- app/src/main/java/com/cswala/cswala/MainActivity.java
Added Explore Fragment as default Fragment.
> Fix #102 Added explore fragment as default

- app/build.gradle
- app/src/main/java/com/cswala/cswala/Fragments/ProfileFragment.java
- app/src/main/res/drawable/ic_baseline_person_24.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values/strings.xml
- build.gradle
implemented necessary changes to resolve the conflicts
I have created the explore fragment as base fragment using fragment manager at MainActivity.java file.
Designed a minimalistic ui for profile segment having several buttons ,profile pic and name .
Fixes #100
> Solved #100 

- app/build.gradle
- app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
- app/src/main/java/com/cswala/cswala/Fragments/ProfileFragment.java
- app/src/main/res/drawable/ic_baseline_person_24.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values/strings.xml
- build.gradle
There were few places where a progress bar was required. So implemented that
Fixes #93
> #93 Progress bar Visibility

- app/build.gradle
- app/src/main/java/com/cswala/cswala/Adapters/JobHuntViewPagerAdapter.java
- app/src/main/java/com/cswala/cswala/Adapters/PortalListAdapter.java
- app/src/main/java/com/cswala/cswala/Fragments/JobFragment.java
- app/src/main/java/com/cswala/cswala/Fragments/JobHunt.java
- app/src/main/java/com/cswala/cswala/Fragments/PortalFragment.java
- app/src/main/java/com/cswala/cswala/Models/PortalListElement.java
- app/src/main/res/layout/fragment_job.xml
- app/src/main/res/layout/fragment_job_hunt.xml
- app/src/main/res/layout/fragment_portal.xml
- app/src/main/res/layout/portal_list_element.xml
- app/src/main/res/values/styles.xml
> Fixes #114 Implemented jobhunt fragment

- app/src/main/java/com/cswala/cswala/Fragments/ExploreFragment.java
- app/src/main/res/anim/item_fall_down_anim.xml
- app/src/main/res/anim/layout_anim_fall_down.xml
- app/src/main/res/layout/fragment_explore.xml
Fixes #124: Added animation to recyclerview items of Explore fragment.
> Fix #124: Add recyclerview item animation

- app/src/main/java/com/cswala/cswala/MainActivity.java
- app/src/main/res/anim/frag_fade_in.xml
- app/src/main/res/anim/frag_fade_out.xml
Fixes #91: Added transition animation when switching between the fragments of the navigation bar.
> Fix #91: Add fragment transition animation

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cswala/cswala/Adapters/LatestNewsAdapter.java
- app/src/main/java/com/cswala/cswala/Fragments/LatestNewsFragment.java
- app/src/main/java/com/cswala/cswala/Fragments/NewsEventsFragment.java
- app/src/main/java/com/cswala/cswala/Fragments/NewsFragment.java
- app/src/main/res/drawable/rounded_corners_button.xml
- app/src/main/res/layout/fragment_latest_news.xml
- app/src/main/res/layout/fragment_news.xml
- app/src/main/res/layout/fragment_news_events.xml
- app/src/main/res/layout/latest_news_element.xml
- app/src/main/res/values/strings.xml
> #115 Implement HackFeed Fragment Done Fully GSSOC21

- app/src/main/res/drawable/navbar_background_land.xml
- app/src/main/res/layout-land/activity_main.xml
Fixes #92: Added landscape variation to the main activity. Positioned nav bar to the left of the screen with vertical orientation.
> Fix #92: Add landscape variation to main activity

- app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
- app/src/main/java/com/cswala/cswala/Activities/LoginWithEmail.java
- app/src/main/java/com/cswala/cswala/Activities/Register.java
- app/src/main/java/com/cswala/cswala/MainActivity.java
- app/src/main/java/com/cswala/cswala/utils/NetworkConnection.java
- app/src/main/res/values/strings.xml
Fixes #109: Added network check before login. Used snackbar to notify connection.
> Fix #109: Add network check on login

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cswala/cswala/Activities/User.java
- app/src/main/java/com/cswala/cswala/Activities/editProfile.java
- app/src/main/java/com/cswala/cswala/Fragments/ProfileFragment.java
- app/src/main/res/layout/activity_edit_profile.xml
- app/src/main/res/layout/color_spinner_layout.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/spinner_dropdown_layout.xml
#
- Fixes #111 : Added edit profile option
#111
> Fixes #111 Added edit profile option 

- app/src/main/res/layout/latest_news_element.xml
- Fix #139 : Part 1:- Improved UI in Hackfeed.
> Improved UI.

- app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
- app/src/main/res/layout/activity_login.xml
Fixes #93: Added progress dialog to login.
> Fix #93: Add progress dialog 

- app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
- app/src/main/java/com/cswala/cswala/MainActivity.java
Fixes #144: Added a confirm dialog to exit on back pressed.
> Fix #144: Add exit dialog

- app/src/main/java/com/cswala/cswala/Adapters/LatestNewsAndEventsPageAdapter.java
- app/src/main/java/com/cswala/cswala/Fragments/NewsFragment.java
- app/src/main/res/layout/fragment_news.xml
Fixes part 2 of #139: Added swipe functionality between Latest News tab and Events tab
> Fix part 2 of #139: Add swipe functionality

- app/src/main/AndroidManifest.xml
Fixes #163: The issue was resolved after declaring WebActivity in Manifest.
> Fix #163: Fix app crash on opening WebActivity

- app/src/main/res/layout-land/activity_login.xml
- Fix #74 : Created landscape variation for login activity.
> Landscape variation in Login activity.

- README.md
- build.gradle
Fix quotes in the build.gradle file.
Update gradle file.
> Fix grammar, indents and whitespace in the README

- app/src/main/res/layout-land/activity_login_with_email.xml
- app/src/main/res/layout-land/activity_register.xml
- app/src/main/res/layout-land/activity_reset_password.xml
- Fix #170 : Created landscape variation for login with email ,reset password, registration
> Added landscape variation.

- app/src/main/java/com/cswala/cswala/Adapters/PortalListAdapter.java
- app/src/main/java/com/cswala/cswala/Fragments/PortalFragment.java
- app/src/main/res/layout/fragment_portal.xml
- build.gradle
> Search Functionality added to job portal

- app/src/main/java/com/cswala/cswala/Adapters/LatestNewsAdapter.java
- app/src/main/java/com/cswala/cswala/Fragments/LatestNewsFragment.java
> latest news are shown in webview

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cswala/cswala/Activities/contestCalendar.java
- app/src/main/java/com/cswala/cswala/Adapters/Api.java
- app/src/main/java/com/cswala/cswala/Adapters/ContestAdapter.java
- app/src/main/java/com/cswala/cswala/Fragments/NewsEventsFragment.java
- app/src/main/java/com/cswala/cswala/Models/Results.java
- app/src/main/java/com/cswala/cswala/Models/contest_Results.java
- app/src/main/res/layout/activity_contest_calendar.xml
- app/src/main/res/layout/contest_item_list.xml
- app/src/main/res/layout/fragment_news_events.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- "Fixes #112 :" Adding calendar feature for CP
> Fix #112 Adding calendar feature for CP

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cswala/cswala/Fragments/CommunityFragment.java
- app/src/main/java/com/cswala/cswala/Models/Message.java
- app/src/main/java/com/cswala/cswala/viewholders/MessageHolder.java
- app/src/main/res/drawable/ic_baseline_attachment_24.xml
- app/src/main/res/drawable/ic_baseline_close_24.xml
- app/src/main/res/layout/fragment_community.xml
- app/src/main/res/layout/message_item_view.xml
Add Image Feature to Community Message. Also Add Progress Bar to get updated that image is been uploaded.
https://user-images.githubusercontent.com/65807152/122168131-84e74800-ce99-11eb-9c7d-c5c34c4658f1.mp4
> Fix:#196 Add Image To Community Message
